#!/bin/bash
#
# Setup Nginx as reverse proxy for n8n (with SSL support)
# This script configures Nginx to proxy requests to n8n
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
DOMAIN=""
ENABLE_SSL=false
EMAIL=""
DEPLOYMENT_DIR="/opt/n8n"

# Usage
usage() {
    cat << EOF
Usage: $0 --domain <domain> [--ssl] [--email <email>]

Setup Nginx as reverse proxy for n8n

Required arguments:
    --domain DOMAIN     Your n8n domain (e.g., n8n.example.com)

Optional arguments:
    --ssl               Enable SSL with Let's Encrypt (requires --email)
    --email EMAIL       Email for Let's Encrypt notifications (required with --ssl)
    --deployment-dir    n8n deployment directory (default: /opt/n8n)

Examples:
    # Without SSL (development/testing)
    $0 --domain n8n.local.dev

    # With SSL (production)
    $0 --domain n8n.example.com --ssl --email admin@example.com

EOF
    exit 1
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --domain)
            DOMAIN="$2"
            shift 2
            ;;
        --ssl)
            ENABLE_SSL=true
            shift
            ;;
        --email)
            EMAIL="$2"
            shift 2
            ;;
        --deployment-dir)
            DEPLOYMENT_DIR="$2"
            shift 2
            ;;
        --help)
            usage
            ;;
        *)
            echo -e "${RED}Error: Unknown argument '$1'${NC}"
            usage
            ;;
    esac
done

# Validate arguments
if [ -z "$DOMAIN" ]; then
    echo -e "${RED}Error: --domain is required${NC}"
    usage
fi

if [ "$ENABLE_SSL" = true ] && [ -z "$EMAIL" ]; then
    echo -e "${RED}Error: --email is required when --ssl is enabled${NC}"
    usage
fi

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}n8n Nginx Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "Domain:         ${GREEN}$DOMAIN${NC}"
echo -e "SSL Enabled:    ${GREEN}$ENABLE_SSL${NC}"
if [ "$ENABLE_SSL" = true ]; then
    echo -e "Email:          ${GREEN}$EMAIL${NC}"
fi
echo -e "Deployment Dir: ${GREEN}$DEPLOYMENT_DIR${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
    exit 1
fi

# Step 1: Check Nginx installation
echo -e "${BLUE}[1/5] Checking Nginx installation...${NC}"
if ! command -v nginx &> /dev/null; then
    echo -e "${YELLOW}Nginx not found. Installing...${NC}"
    
    # Detect OS and install
    if [ -f /etc/debian_version ]; then
        apt-get update
        apt-get install -y nginx
    elif [ -f /etc/redhat-release ]; then
        yum install -y nginx
    else
        echo -e "${RED}Error: Unsupported OS. Please install nginx manually.${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✓ Nginx installed${NC}"
else
    echo -e "${GREEN}✓ Nginx already installed${NC}"
fi

# Step 2: Create Nginx configuration
echo -e "${BLUE}[2/5] Creating Nginx configuration...${NC}"

if [ "$ENABLE_SSL" = true ]; then
    # SSL configuration (HTTP will redirect to HTTPS, HTTPS configured)
    cat > "/etc/nginx/sites-available/n8n" << EOF
# n8n Nginx Configuration (with SSL)
# Auto-generated by setup-nginx.sh

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    # Redirect all HTTP to HTTPS
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN};

    # SSL Configuration (managed by Certbot)
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    # Increase upload size for n8n workflows
    client_max_body_size 50M;

    # Access and Error logs
    access_log /var/log/nginx/n8n-access.log;
    error_log /var/log/nginx/n8n-error.log;

    # Proxy to n8n Docker container
    location / {
        proxy_pass http://127.0.0.1:5678;
        proxy_http_version 1.1;
        
        # WebSocket support (required for n8n)
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Standard proxy headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        
        # Timeouts
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
        send_timeout 300;
    }

    # Health check endpoint (optional - for monitoring)
    location /healthz {
        proxy_pass http://127.0.0.1:5678/healthz;
        access_log off;
    }
}
EOF
else
    # Non-SSL configuration (HTTP only, for development/testing)
    cat > "/etc/nginx/sites-available/n8n" << EOF
# n8n Nginx Configuration (HTTP only)
# Auto-generated by setup-nginx.sh
# WARNING: This configuration is NOT secure for production use

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Increase upload size for n8n workflows
    client_max_body_size 50M;

    # Access and Error logs
    access_log /var/log/nginx/n8n-access.log;
    error_log /var/log/nginx/n8n-error.log;

    # Proxy to n8n Docker container
    location / {
        proxy_pass http://127.0.0.1:5678;
        proxy_http_version 1.1;
        
        # WebSocket support (required for n8n)
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Standard proxy headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        
        # Timeouts
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
        send_timeout 300;
    }

    # Health check endpoint
    location /healthz {
        proxy_pass http://127.0.0.1:5678/healthz;
        access_log off;
    }
}
EOF
fi

echo -e "${GREEN}✓ Nginx configuration created${NC}"

# Step 3: Enable site
echo -e "${BLUE}[3/5] Enabling Nginx site...${NC}"

# Create sites-enabled directory if it doesn't exist
mkdir -p /etc/nginx/sites-enabled

# Remove existing symlink if present
if [ -L "/etc/nginx/sites-enabled/n8n" ]; then
    rm "/etc/nginx/sites-enabled/n8n"
fi

# Create symlink
ln -s /etc/nginx/sites-available/n8n /etc/nginx/sites-enabled/n8n

echo -e "${GREEN}✓ Site enabled${NC}"

# Step 4: Test Nginx configuration
echo -e "${BLUE}[4/5] Testing Nginx configuration...${NC}"
if ! nginx -t; then
    echo -e "${RED}Error: Nginx configuration test failed${NC}"
    echo -e "${YELLOW}Rolling back changes...${NC}"
    rm -f /etc/nginx/sites-enabled/n8n
    exit 1
fi
echo -e "${GREEN}✓ Nginx configuration is valid${NC}"

# Step 5: Setup SSL if enabled
if [ "$ENABLE_SSL" = true ]; then
    echo -e "${BLUE}[5/5] Setting up SSL certificate...${NC}"
    
    # First, reload Nginx with HTTP-only config to allow Certbot validation
    systemctl reload nginx
    
    # Run SSL setup script
    if [ -f "${DEPLOYMENT_DIR}/scripts/setup-ssl.sh" ]; then
        bash "${DEPLOYMENT_DIR}/scripts/setup-ssl.sh" --domain "$DOMAIN" --email "$EMAIL"
    else
        echo -e "${YELLOW}setup-ssl.sh not found. Running Certbot directly...${NC}"
        
        # Install Certbot if not present
        if ! command -v certbot &> /dev/null; then
            if [ -f /etc/debian_version ]; then
                apt-get install -y certbot python3-certbot-nginx
            elif [ -f /etc/redhat-release ]; then
                yum install -y certbot python3-certbot-nginx
            fi
        fi
        
        # Obtain certificate
        certbot --nginx \
            --non-interactive \
            --agree-tos \
            --email "$EMAIL" \
            --domain "$DOMAIN" \
            --redirect
    fi
else
    echo -e "${BLUE}[5/5] Reloading Nginx...${NC}"
    systemctl enable nginx
    systemctl reload nginx
    echo -e "${GREEN}✓ Nginx reloaded${NC}"
fi

# Display success message
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Nginx Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

if [ "$ENABLE_SSL" = true ]; then
    echo -e "${GREEN}Your n8n instance is now accessible at:${NC}"
    echo -e "${BLUE}https://$DOMAIN${NC}"
    echo ""
    echo -e "${YELLOW}Important: Update your .env file with:${NC}"
    echo -e "${BLUE}N8N_PROTOCOL=https${NC}"
    echo -e "${BLUE}N8N_HOST=$DOMAIN${NC}"
    echo -e "${BLUE}WEBHOOK_URL=https://$DOMAIN${NC}"
else
    echo -e "${GREEN}Your n8n instance is now accessible at:${NC}"
    echo -e "${BLUE}http://$DOMAIN${NC}"
    echo ""
    echo -e "${YELLOW}Important: Update your .env file with:${NC}"
    echo -e "${BLUE}N8N_PROTOCOL=http${NC}"
    echo -e "${BLUE}N8N_HOST=$DOMAIN${NC}"
    echo -e "${BLUE}WEBHOOK_URL=http://$DOMAIN${NC}"
    echo ""
    echo -e "${RED}WARNING: HTTP is not secure for production!${NC}"
    echo -e "${RED}Run with --ssl flag to enable HTTPS.${NC}"
fi

echo ""
echo -e "${YELLOW}Then restart n8n containers:${NC}"
echo -e "${BLUE}cd $DEPLOYMENT_DIR && docker compose restart${NC}"
echo ""
echo -e "${GREEN}Configuration files:${NC}"
echo -e "  Nginx config: /etc/nginx/sites-available/n8n"
echo -e "  Access log:   /var/log/nginx/n8n-access.log"
echo -e "  Error log:    /var/log/nginx/n8n-error.log"
